# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/zenner_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 670)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 211, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("designer/../images/zenner_logo.png"))
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 321, 321))
        self.plainTextEdit.setStyleSheet("font: 14pt \"Arial\";")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.exec_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exec_btn.setGeometry(QtCore.QRect(10, 450, 321, 31))
        self.exec_btn.setStyleSheet("background-color: rgb(110, 161, 255);\n"
"")
        self.exec_btn.setObjectName("exec_btn")
        self.open_folder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_folder_btn.setGeometry(QtCore.QRect(10, 490, 321, 31))
        self.open_folder_btn.setStyleSheet("background-color: rgb(175, 255, 178);")
        self.open_folder_btn.setObjectName("open_folder_btn")
        self.open_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_file_btn.setGeometry(QtCore.QRect(10, 530, 321, 31))
        self.open_file_btn.setStyleSheet("background-color: rgb(175, 255, 178);\n"
"")
        self.open_file_btn.setObjectName("open_file_btn")
        self.clear_folder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_folder_btn.setGeometry(QtCore.QRect(10, 570, 321, 31))
        self.clear_folder_btn.setStyleSheet("background-color: rgb(255, 92, 108);")
        self.clear_folder_btn.setObjectName("clear_folder_btn")
        self.exit_qt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_qt_btn.setGeometry(QtCore.QRect(10, 610, 321, 31))
        self.exit_qt_btn.setStyleSheet("background-color: rgb(255, 92, 108);\n"
"")
        self.exit_qt_btn.setObjectName("exit_qt_btn")
        self.msg_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.msg_check_box.setGeometry(QtCore.QRect(10, 415, 101, 21))
        self.msg_check_box.setObjectName("msg_check_box")
        self.clear_text_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.clear_text_check_box.setGeometry(QtCore.QRect(130, 410, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clear_text_check_box.setFont(font)
        self.clear_text_check_box.setObjectName("clear_text_check_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zenner barcode generator"))
        self.exec_btn.setText(_translate("MainWindow", "Выполнить генерацию штрихкодов"))
        self.open_folder_btn.setText(_translate("MainWindow", "Открыть папку со штрих_кодами"))
        self.open_file_btn.setText(_translate("MainWindow", "Открыть файл inner_report.txt"))
        self.clear_folder_btn.setText(_translate("MainWindow", "Очистить папку со штрих_кодами"))
        self.exit_qt_btn.setText(_translate("MainWindow", "Выход"))
        self.msg_check_box.setText(_translate("MainWindow", "Сообщения"))
        self.clear_text_check_box.setText(_translate("MainWindow", "Очищать введенные номера \n"
"после генерации"))
